apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  type: ClusterIP   # Internal access only
  ports:
    - port: 10001         # Service port
      targetPort: 10001   # Container port
      protocol: TCP
      name: http
  selector:
    app: auth-service
