apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  type: NodePort
  ports:
    - port: 10001
      targetPort: 10001
      nodePort: 30077   # in allowed range
      protocol: TCP
      name: http
  selector:
    app: auth-service
