# Server configuration
# Uncomment and set the context path if needed
# server:
#   servlet:
#     context-path: /your-context-path
server:
  port: 10001

# Logging configuration
log:
  collectionName: UserAuthLog
#
#spring:
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.Oracle12cDialect


# Security settings
security:
  ignored: /**/public

# Email connector API
connector:
  email:
    send:
      api: https://connector.r-sharma.in/email-connector/send-mail
