# Server configuration

spring:
  application:
    name: AUTH-SERVICE

server:
  port: 10001

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/  # Eureka server URL
    fetchRegistry: true    # Fetch registry to discover other services
    registerWithEureka: true  # Register itself with Eureka
  instance:
    preferIpAddress: true  # Use Pod IP instead of hostname (better for K8s)

# Logging configuration
log:
  collectionName: UserAuthLog

# Security settings
security:
  ignored: /**/public

# Email connector API
connector:
  email:
    send:
      api: https://connector.guardianservices.in/email-connector/send-mail


pass:
  manager:
    user:
      create:
        url: https://auth.guardianservices.in/password-manager/create-user




management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
