# Server configuration

spring:
  application:
    name: auth-service

server:
  port: 10001

eureka:
  client:
    service-url:
      defaultZone: https://eureka.guardianservices.in/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# Logging configuration
log:
  collectionName: UserAuthLog

# Security settings
security:
  ignored: /**/public

# Email connector API
connector:
  email:
    send:
      api: https://connector.guardianservices.in/email-connector/send-mail


pass:
  manager:
    user:
      create:
        url: https://auth.guardianservices.in/password-manager/create-user