spring:
  application:
    name: AUTH-SERVICE

server:
  port: 10001
  servlet:
    context-path: /auth-service

# Direct internal URL of Email Service (K8s DNS or Docker Compose service name)
email:
  service:
    url: http://email-connector-service:10002

log:
  collectionName: UserAuthLog

security:
  ignored: /**/public


# Email connector API
connector:
  email:
    send:
      api: https://connector.guardianservices.in/email-connector/send-mail


pass:
  manager:
    user:
      create:
        url: https://auth.guardianservices.in/password-manager/create-user

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
