# Server configuration
# Uncomment and set the context path if needed
# server:
#   servlet:
#     context-path: /your-context-path
server:
  port: 10001
  address: 0.0.0.0

# Logging configuration
log:
  collectionName: UserAuthLog

# Security settings
security:
  ignored: /**/public

# Email connector API
connector:
  email:
    send:
      api: https://connector.guardianservices.in/email-connector/send-mail


pass:
  manager:
    user:
      create:
        url: https://passmanager.guardianservices.in/password-manager/create-user