spring:
  application:
    name: AUTH-SERVICE

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_URL:https://keycloak.guardianservices.in}/realms/${KEYCLOAK_REALM:guardian-service}/protocol/openid-connect/certs

server:
  port: 10001

# Direct internal URL of Email Service (K8s DNS or Docker Compose service name)
email:
  service:
    url: http://email-connector-service:10002

log:
  collectionName: UserAuthLog

security:
  ignored: /**/public


# Email connector API
connector:
  email:
    send:
      api: https://connector.guardianservices.in/email-connector/send-mail


pass:
  manager:
    user:
      create:
        url: https://auth.guardianservices.in/password-manager/create-user

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
